repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0  # Use the ref you want to point at
  hooks:
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "" # Use the sha or tag you want to point at
  hooks:
    - id: prettier


-   repo: https://github.com/asottile/dead
    rev: v1.5.2
    hooks:
    -   id: dead
